### ISSUE TITLE
Logo in "branding" or style.css not effective

### ISSUE THREAD

**Issue by zoperado** [phillip-kruger/openapi-example#1]
Placing artefacts under META-INF/branding aren't picked up. Is `branding` hardcoded or does it need to be specified in `application.properties`?

**Comment by phillip-kruger** [comment]
branding is hardcoded. Can you provide more details as this works for me. What does not work for you ? Can you provide screenshots ?

**Comment by phillip-kruger** [comment]
@zoperado - also note that when changing the branding you need to 1) Rebuild and then run 2) make sure your browser is not caching the old files by forcing cache clear or opening the page in private/incognito mode

**Comment by phillip-kruger** [comment]
Any feedback ? Closing, please reopen if you believe this is still an issue.

**Comment by zoperado** [comment]
It seems to have been caching indeed. Mea culpa.
